version: '3'
services:
  db:
    image: postgres:9.6-alpine
    volumes:
      - ./db/data:/var/lib/postgresql/data
      - ./db/init.d:/docker-entrypoint-initdb.d
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
  worker-1:
    build:
      context: .
      dockerfile: build/Dockerfile
    image: "grus/cms:1"
    expose:
      - 26000
    volumes:
      - ./config/cms.conf:/usr/local/etc/cms.conf
    environment:
      CMS_INSTANCE_TYPE: WORKER
    depends_on:
      - db
  worker-2:
    build:
      context: .
      dockerfile: build/Dockerfile
    image: "grus/cms:1"
    expose:
      - 26000
    volumes:
      - ./config/cms.conf:/usr/local/etc/cms.conf
    environment:
      CMS_INSTANCE_TYPE: WORKER
    depends_on:
      - db
  worker-3:
    build:
      context: .
      dockerfile: build/Dockerfile
    image: "grus/cms:1"
    expose:
      - 26000
    volumes:
      - ./config/cms.conf:/usr/local/etc/cms.conf
    environment:
      CMS_INSTANCE_TYPE: WORKER
    depends_on:
      - db
  ranking:
    build:
      context: .
      dockerfile: build/Dockerfile
    image: "grus/cms:1"
    expose:
      - 8890
    volumes:
      - ./config/cms.ranking.conf:/usr/local/etc/cms.ranking.conf
    environment:
      CMS_INSTANCE_TYPE: RANKING
    depends_on:
      - db
  main:
    build: 
      context: .
      dockerfile: build/Dockerfile
    image: "grus/cms:1"
    expose:
      - 8888
      - 8889 
    volumes:
      - ./config/cms.conf:/usr/local/etc/cms.conf
    environment:
      CMS_INSTANCE_TYPE: MAIN
      CMS_CONTEST_ID: 1 
    depends_on:
      - db
      - ranking 
      - worker-1 
      - worker-2
      - worker-3
  proxy:
    image: nginx:1.17-alpine
    volumes:
      - ./config/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - main
      - ranking
    ports:
      - 80:80

